interface ContentData {
	id: number;
	title: string;
	text?: string;
}

interface BestSellerData {
	tag?: string;
	title: string;
	description: string;
	content: ContentData[];
	images: string[];
}

export const bestSellerData: BestSellerData = {
	tag: "Fashion as unique as you are",
	title: "Best Seller",
	description:
		"Welcome to our Best Sellers collection, where you can discover our most sought-after fashion pieces that are loved by our customers.",
	images: ["/assets/images/page/homepage1/img-product-2.png"],
	content: [
		{
			id: 1,
			title: "Stay on-trend",
			text: "Explore our Best Sellers collection for the latest fashion trends that are making waves in the industry.",
		},
		{
			id: 2,
			title: "Customer Favorites",
			text: "Discover our most-loved fashion pieces, as recommended by our valued customers.",
		},
		{
			id: 3,
			title: "Uncompromising Quality",
			text: "Shop from our Best Sellers collection, where fashion meets exceptional craftsmanship and high-quality materials.",
		},
		{
			id: 4,
			title: "Versatile Style",
			text: "Find versatile fashion pieces that effortlessly elevate your wardrobe for any occasion.",
		},
	],
};

export const secondBestSellerData: BestSellerData = {
	tag: "For You",
	title: "Best Seller",
	description:
		"Welcome to our Best Sellers collection, where you can discover our most sought-after fashion pieces that are loved by our customers.",
	images: [
		"/assets/images/page/homepage2/img-best-seller.png",
		"/assets/images/page/homepage2/img-best-seller-2.png",
	],
	content: [
		{
			id: 1,
			title: "Stay on-trend",
			text: "Explore our Best Sellers collection for the latest fashion trends that are making waves in the industry.",
		},
		{
			id: 2,
			title: "Customer Favorites",
			text: "Discover our most-loved fashion pieces, as recommended by our valued customers.",
		},
		{
			id: 3,
			title: "Uncompromising Quality",
			text: "Shop from our Best Sellers collection, where fashion meets exceptional craftsmanship and high-quality materials.",
		},
		{
			id: 4,
			title: "Versatile Style",
			text: "Find versatile fashion pieces that effortlessly elevate your wardrobe for any occasion.",
		},
	],
};

export const thirdBestSellerData: BestSellerData = {
	tag: "For You",
	title: "Best Seller",
	description:
		"Welcome to our Best Sellers collection, where you can discover our most sought-after fashion pieces that are loved by our customers.",
	images: ["/assets/images/page/homepage6/img-1.png"],
	content: [
		{
			id: 1,
			title: "Stay on-trend",
		},
		{
			id: 2,
			title: "Customer Favorites",
		},
		{
			id: 3,
			title: "Uncompromising Quality",
		},
		{
			id: 4,
			title: "Versatile Style",
		},
	],
};

export const fourthBestSellerData4: BestSellerData = {
	title: "Shopping Process",
	description: "How it works",
	images: [
		"/assets/images/page/homepage7/img-1.png",
		"/assets/images/page/homepage7/chart-2.png",
		"/assets/images/page/homepage7/img-safety.png",
	],
	content: [
		{
			id: 1,
			title: "Input",
			text: "Enter your references and personal information.",
		},
		{
			id: 2,
			title: "Item suggestion",
			text: "Exclusive item recommendations generated by AI based on your input.",
		},
		{
			id: 3,
			title: "Try out",
			text: "The latest design trends meet hand-crafted templates.",
		},
		{
			id: 4,
			title: "Payment",
			text: "The latest design trends meet hand-crafted templates.",
		},
	],
};

export const fifthBestSellerData: BestSellerData = {
	tag: "Fashion as unique as you are",
	title: "Best Seller",
	description:
		"Welcome to our Best Sellers collection, where you can discover our most sought-after fashion pieces that are loved by our customers.",
	images: ["/assets/images/page/about/3/img-4.png"],
	content: [
		{
			id: 1,
			title: "Stay on-trend",
			text: "Explore our Best Sellers collection for the latest fashion trends that are making waves in the industry.",
		},
		{
			id: 2,
			title: "Customer Favorites",
			text: "Discover our most-loved fashion pieces, as recommended by our valued customers.",
		},
		{
			id: 3,
			title: "Uncompromising Quality",
			text: "Shop from our Best Sellers collection, where fashion meets exceptional craftsmanship and high-quality materials.",
		},
		{
			id: 4,
			title: "Versatile Style",
			text: "Find versatile fashion pieces that effortlessly elevate your wardrobe for any occasion.",
		},
	],
};

export const sixthBestSellerData: BestSellerData = {
	tag: "Built Exclusively For You",
	title: "Precision Fixes: Quality Commitment for Your Clothes",
	description:
		"Precision fixes for your clothes with quality craftsmanship. Our skilled tailors ensure impeccable results using premium materials and techniques. Affordable pricing and dedicated customer care. Discover the difference today!",
	images: [
		"/assets/images/page/services/1/img-built-1.png",
		"/assets/images/page/services/1/img-built-2.png",
	],
	content: [
		{
			id: 1,
			title: "Precise Alterations",
			text: "Our skilled tailors provide meticulous alterations, ensuring every adjustment is crafted with precision.",
		},
		{
			id: 2,
			title: "Quality Materials & Techniques",
			text: "We use premium materials and proven techniques for fixing clothes, ensuring durability and impeccable results.",
		},
		{
			id: 3,
			title: "Affordable Pricing",
			text: "We offer competitive pricing for our fixing services without compromising on quality.",
		},
		{
			id: 4,
			title: "Dedicated Customer Care",
			text: "We provide attentive customer care to address any post-repair inquiries or concerns, ensuring your satisfaction.",
		},
	],
};
